name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: sudo apt-get install pngquant
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material[imaging]
      - run: mkdocs build
      - name: SFTP Sync
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: ${{ secrets.SFTP_HOST }}
          user: ${{ secrets.SFTP_USR }}
          user_private_key: "${{ secrets.SFTP_KEY }}"
          host_public_key: ""
          remote: /
          mirror_options: "--exclude-glob=.git*/ --verbose"
      # - name: SFTP uploader
      #   uses: wangyucode/sftp-upload-action@v2.0.2
      #   with:
      #     host: ${{ secrets.SFTP_HOST }}
      #     username: ${{ secrets.SFTP_USR }}
      #     password: ${{ secrets.SFTP_PWD }}
      #     compress: true
      #     forceUpload: true
      #     localDir: './site'
      #     remoteDir: '/'
